//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHAHmeHmood_MVC5fourth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int stuId { get; set; }
        public string StuName { get; set; }
        public string Semester { get; set; }
    }
}
